### PR TITLE
AMOL port

### PR DESCRIPTION
**Pull request by IcemarkUK**

### CODE REVIEW

**Comment by rh101** [comment]
Just FYI, there are files missing from the root directory, which are generated when the "axmol new" command is used. Those files are referenced in the `CMakeLists.txt` for Windows builds:

For example, the `run.bat.in` file:
```
# config quick starter batch script run.bat for windows
if(WIN32)
    file(RELATIVE_PATH CMAKE_BUILD_RELATIVE_DIR "${CMAKE_CURRENT_SOURCE_DIR}" "${PROJECT_BINARY_DIR}")
    configure_file("${CMAKE_CURRENT_SOURCE_DIR}/run.bat.in" "${CMAKE_CURRENT_SOURCE_DIR}/run.bat" @ONLY)
endif()
```

Either the `CMakeLists.txt` needs to change, or those files need to be included in the repo in order for the cmake build to work.

**Comment by IcemarkUK** [comment]
Thanks I've not looked at the windows build or the android one, so there may be files etc that I've not put in the right place. I've not updated the project files for example. And  there might be compilation issues cause by the changes in build process.  Let me at least try and move the windows one in ...

Hmm, so the content thing is a change in the way axmol sets up the resources than when cocos did it.

I have it that way so that I can easily swap between the 3 variants without keep copying files around.

**Comment by rh101** [comment]
> Hmm, so the content thing is a change in the way axmol sets up the resources than when cocos did it.
> 

Yes, it has changed, and it was meant to prevent copying resources unnecessarily to the build folder. It only affects Windows builds. You should be able to change your project CMakeLists.txt to do what cocos2d-x did, which is to copy all resources to the output Content folder.  Just add the required cmake functions from here: https://github.com/cocos2d/cocos2d-x/blob/v4/cmake/Modules/CocosBuildHelpers.cmake (`cocos_copy_target_res` etc.)

**Comment by IcemarkUK** [comment]
> Yes, it has changed, and it was meant to prevent copying resources unnecessarily to the build folder. It only affects Windows builds. You should be able to change your project CMakeLists.txt to do what cocos2d-x did, which is to copy all resources to the output Content folder. Just add the required cmake functions from here: https://github.com/cocos2d/cocos2d-x/blob/v4/cmake/Modules/CocosBuildHelpers.cmake (`cocos_copy_target_res` etc.)

I've not looked at the Android version yet. I've always run the Android version from the project itself - not sure if you do, or ever used to generate a project like you do with OSX/iOS/Windows - but I have something in my grade file that use to make Android work.

https://github.com/ChilliHugger/The-Lords-Of-Midnight/blob/96484890cfaa2141f09a862cd45fd4c7b4484874/main/midnight/cocosProjects/proj.android_midnight/app/build.gradle#L29-L37

**Comment by rh101** [comment]
> I've not looked at the Android version yet. I've always run the Android version from the project itself - not sure if you do, or ever used to generate a project like you do with OSX/iOS/Windows - but I have something in my grade file that use to make Android work.

Correct, Android doesn't have the same process as the other platforms, since Android Studio takes care of generating the relevant files automatically via cmake, every time you use the gradle sync option.

**Comment by rh101** [comment]
Strange error in `default_scenario.cpp`:

```
COMMAND ( PropMapSize )
        {
            argv[0]=(s32)2;
            argv[1]=mx->gamemap->Size().cx;
            argv[2]=mx->gamemap->Size().cy;
            return MX_OK ;
        }
```

Had to change it to this in order for it to compile:
```
COMMAND ( PropMapSize )
        {
            argv[0]=(s32)2;
            argv[1]=(s32)mx->gamemap->Size().cx;
            argv[2]=(s32)mx->gamemap->Size().cy;
            return MX_OK ;
        }
```

**Comment by IcemarkUK** [comment]
> Strange error in `default_scenario.cpp`:
> 
> ```
> COMMAND ( PropMapSize )
>         {
>             argv[0]=(s32)2;
>             argv[1]=mx->gamemap->Size().cx;
>             argv[2]=mx->gamemap->Size().cy;
>             return MX_OK ;
>         }
> ```

I suspect some things like this will come out of either the change to c++20 or something with a different/newer VS build process. At the moment @fassisrosa builds for me on Windows, so he usually has the job of fixing up anything VS doesn't like compared to Xcode :)

**Pull request closed without merging**
